image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - test

test_async:
  stage: test
  services:
   - trufflesuite/ganache-cli
  script:
   - echo "MNEMONIC"=$MNEMONIC >> ".env"
   - export NODE_OPTIONS=--openssl-legacy-provider
   - npm install truffle
   - ./node_modules/truffle/build/cli.bundled.js compile
   - ./node_modules/truffle/build/cli.bundled.js migrate --network ropsten
   - ./node_modules/truffle/build/cli.bundled.js test --network ropsten
